kind: pipeline
type: docker
name: subsora-ci

volumes:
  - name: dockersock
    temp: {}

services:
  - name: docker
    image: docker:20.10.14-dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

trigger:
  branch: [master]
  event: [push]

steps:
  # ===========================================================================
  # Шаги для BACKEND
  # ===========================================================================
  - name: build and push backend
    image: docker:20.10.14
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      DOCKER_USERNAME: { from_secret: docker_username }
      DOCKER_PASSWORD: { from_secret: docker_password }
    commands:
      - |
        timeout=20
        while ! docker ps > /dev/null 2>&1; do sleep 1; timeout=$(expr $timeout - 1); if [ $timeout -eq 0 ]; then echo "Dind failed to start."; exit 1; fi; done
      - echo $DOCKER_PASSWORD | docker login cicd.zerity.ru:55000 -u $DOCKER_USERNAME --password-stdin
      # --- ВОТ ОНО, РЕШЕНИЕ ---
      - docker build --network=host -t subsora-backend -f backend/Dockerfile ./backend
      - docker tag subsora-backend cicd.zerity.ru:55000/subsora/backend:latest
      - docker push cicd.zerity.ru:55000/subsora/backend:latest
    when:
      change:
        includes:
          - backend/**

  - name: deploy backend
    image: appleboy/drone-ssh
    settings: { host: { from_secret: ssh_host }, username: { from_secret: ssh_user }, key: { from_secret: ssh_key } }
    script:
      - |
        set -ex
        cd ~/subsora
        git pull origin master
        echo $$DOCKER_PASSWORD | docker login cicd.zerity.ru:55000 -u $$DOCKER_USERNAME --password-stdin
        docker-compose pull backend
        docker-compose up -d --no-deps backend
        echo "✅ Backend deployment successful!"
    environment: { DOCKER_USERNAME: { from_secret: docker_username }, DOCKER_PASSWORD: { from_secret: docker_password } }
    when:
      change:
        includes:
          - backend/**
