"""dd plan_id to transactions table

Revision ID: 6bf582fc5cb8
Revises: 109512d4706b
Create Date: 2025-07-29 01:46:46.559102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf582fc5cb8'
down_revision: Union[str, Sequence[str], None] = '109512d4706b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'plan_id')
    # ### end Alembic commands ###
